//About errror handling:
try{
    console.log(x);
}catch(e)
{
    console.log(e);
}